<?php
/**
 * Data access for pqbg_codes, enforcing the one-active-code-per-item invariant
 * in the application layer. The UNIQUE(active_product_id) index and the
 * optional CHECK constraint are defence in depth behind these rules:
 *
 *   - An item (simple product or variation) has at most one active code.
 *   - Creating a code for an item that already has an active one is rejected.
 *   - Retiring clears active_product_id in the same UPDATE.
 *   - There is deliberately no "reactivate": a retired code can never become
 *     active again. Replacing a code means retire + create a new one.
 *
 * This class performs NO capability checks; callers (admin screens, REST
 * routes in later phases) must check Permissions::can_manage_codes() first.
 * It does not generate codes or validate WooCommerce product types either:
 * CodeGenerator produces codes and ProductCodeService decides eligibility.
 *
 * @package ProductQrBarcode
 */

namespace ProductQrBarcode;

use WP_Error;

defined( 'ABSPATH' ) || exit;

/**
 * Reads and writes product-code rows.
 */
final class CodeRepository {

	const KIND_PRODUCT = 'product';

	const STATUS_ACTIVE  = 'active';
	const STATUS_RETIRED = 'retired';

	/** Uppercase letters, digits and inner hyphens, 4-32 chars (e.g. DC-XXXX-XXXX-XXXX). */
	const CODE_PATTERN = '/^[A-Z0-9][A-Z0-9-]{2,30}[A-Z0-9]$/';

	/**
	 * Normalises a code for storage/lookup: trimmed and uppercased. Returns '' when invalid.
	 *
	 * @param string $code Raw code.
	 */
	public static function normalize_code( string $code ): string {
		$code = strtoupper( trim( $code ) );

		return preg_match( self::CODE_PATTERN, $code ) ? $code : '';
	}

	/**
	 * Finds a code row by its code string.
	 *
	 * @param string $code Code string.
	 * @return array<string, string>|null
	 */
	public static function find_by_code( string $code ): ?array {
		global $wpdb;

		$code = self::normalize_code( $code );

		if ( '' === $code ) {
			return null;
		}

		$table = Schema::codes_table();
		$row   = $wpdb->get_row( $wpdb->prepare( "SELECT * FROM {$table} WHERE code = %s", $code ), ARRAY_A ); // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared -- fixed identifier.

		return is_array( $row ) ? $row : null;
	}

	/**
	 * Whether a code string has ever been issued, active or retired. Retired
	 * codes count, so a retired code is never handed out again.
	 *
	 * An invalid code string is reported as taken so callers never try to use it.
	 *
	 * @param string $code Code string.
	 */
	public static function code_exists( string $code ): bool {
		global $wpdb;

		$code = self::normalize_code( $code );

		if ( '' === $code ) {
			return true;
		}

		$table = Schema::codes_table();

		return null !== $wpdb->get_var( $wpdb->prepare( "SELECT 1 FROM {$table} WHERE code = %s LIMIT 1", $code ) ); // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared -- fixed identifier.
	}

	/**
	 * Finds the active code row for a purchasable item.
	 *
	 * @param int $product_id Simple product or variation ID.
	 * @return array<string, string>|null
	 */
	public static function find_active_for_product( int $product_id ): ?array {
		global $wpdb;

		if ( $product_id <= 0 ) {
			return null;
		}

		$table = Schema::codes_table();
		$row   = $wpdb->get_row( $wpdb->prepare( "SELECT * FROM {$table} WHERE active_product_id = %d", $product_id ), ARRAY_A ); // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared -- fixed identifier.

		return is_array( $row ) ? $row : null;
	}

	/**
	 * Inserts a new active code for an item.
	 *
	 * Runs in its own transaction; do not call it inside another open
	 * transaction (START TRANSACTION implicitly commits the outer one).
	 *
	 * @param string $code       Code string (already generated by the caller).
	 * @param int    $product_id Simple product or variation ID.
	 * @param int    $parent_id  Variation's parent product ID, or 0 for simple products.
	 * @param int    $user_id    User creating the code.
	 * @return int|WP_Error New row ID.
	 */
	public static function create_active( string $code, int $product_id, int $parent_id, int $user_id ) {
		global $wpdb;

		$code = self::normalize_code( $code );

		if ( '' === $code ) {
			return new WP_Error( 'pqbg_invalid_code', __( 'Invalid product code format.', 'product-qrcode-barcode-generator' ) );
		}

		if ( $product_id <= 0 || $parent_id < 0 || $parent_id === $product_id || $user_id < 0 ) {
			return new WP_Error( 'pqbg_invalid_item', __( 'Invalid product reference.', 'product-qrcode-barcode-generator' ) );
		}

		$table = Schema::codes_table();

		$wpdb->query( 'START TRANSACTION' );

		// Locks the item's slot in the unique index so concurrent creators serialise here.
		$existing = $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$table} WHERE active_product_id = %d FOR UPDATE", $product_id ) ); // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared -- fixed identifier.

		if ( null !== $existing ) {
			$wpdb->query( 'ROLLBACK' );
			return new WP_Error( 'pqbg_active_code_exists', __( 'This item already has an active product code.', 'product-qrcode-barcode-generator' ) );
		}

		$suppress = $wpdb->suppress_errors( true );
		$inserted = $wpdb->insert(
			$table,
			array(
				'code'              => $code,
				'kind'              => self::KIND_PRODUCT,
				'product_id'        => $product_id,
				'parent_id'         => $parent_id,
				'active_product_id' => $product_id,
				'status'            => self::STATUS_ACTIVE,
				'created_at_gmt'    => current_time( 'mysql', true ),
				'created_by'        => $user_id,
			),
			array( '%s', '%s', '%d', '%d', '%d', '%s', '%s', '%d' )
		);
		$wpdb->suppress_errors( $suppress );

		if ( false === $inserted ) {
			$wpdb->query( 'ROLLBACK' );
			// Unique index on code or active_product_id caught a duplicate/race.
			return new WP_Error( 'pqbg_code_conflict', __( 'The product code could not be saved because it conflicts with an existing code.', 'product-qrcode-barcode-generator' ) );
		}

		$id = (int) $wpdb->insert_id;
		$wpdb->query( 'COMMIT' );

		return $id;
	}

	/**
	 * Active code rows for many items at once, in one query.
	 *
	 * @param int[] $product_ids Simple product or variation IDs.
	 * @return array<int, array<string, string>> Rows keyed by product ID; items without an active code are absent.
	 */
	public static function find_active_for_products( array $product_ids ): array {
		global $wpdb;

		$ids = array_values( array_unique( array_filter( array_map( 'intval', $product_ids ), static fn( $id ) => $id > 0 ) ) );

		if ( array() === $ids ) {
			return array();
		}

		$table        = Schema::codes_table();
		$placeholders = implode( ',', array_fill( 0, count( $ids ), '%d' ) );
		$rows         = $wpdb->get_results( $wpdb->prepare( "SELECT * FROM {$table} WHERE active_product_id IN ({$placeholders})", $ids ), ARRAY_A ); // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared,WordPress.DB.PreparedSQLPlaceholders.UnfinishedPrepare -- fixed identifier, one %d per ID.

		$map = array();

		foreach ( (array) $rows as $row ) {
			$map[ (int) $row['product_id'] ] = $row;
		}

		return $map;
	}

	/**
	 * Active code rows whose parent is the given product (a variable product's variations).
	 *
	 * @param int $parent_id Parent product ID.
	 * @return array<int, array<string, string>>
	 */
	public static function find_active_by_parent( int $parent_id ): array {
		global $wpdb;

		if ( $parent_id <= 0 ) {
			return array();
		}

		$table = Schema::codes_table();
		$rows  = $wpdb->get_results( $wpdb->prepare( "SELECT * FROM {$table} WHERE parent_id = %d AND status = %s", $parent_id, self::STATUS_ACTIVE ), ARRAY_A ); // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared -- fixed identifier.

		return is_array( $rows ) ? $rows : array();
	}

	/**
	 * Retired code history for an item, or for a variable product and all its
	 * variations (including variations that have since been deleted). Newest first.
	 *
	 * @param int $product_id Product or variation ID.
	 * @param int $limit      Maximum rows.
	 * @return array<int, array<string, string>>
	 */
	public static function find_retired_for_product_or_parent( int $product_id, int $limit = 50 ): array {
		global $wpdb;

		if ( $product_id <= 0 ) {
			return array();
		}

		$table = Schema::codes_table();
		$rows  = $wpdb->get_results(
			$wpdb->prepare(
				"SELECT * FROM {$table} WHERE status = %s AND ( product_id = %d OR parent_id = %d ) ORDER BY retired_at_gmt DESC, id DESC LIMIT %d", // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared -- fixed identifier.
				self::STATUS_RETIRED,
				$product_id,
				$product_id,
				max( 1, $limit )
			),
			ARRAY_A
		);

		return is_array( $rows ) ? $rows : array();
	}

	/**
	 * Atomically replaces an item's active code: in ONE transaction, with the
	 * item's active row locked, retires the current code and inserts the new one.
	 *
	 * Guarantees: never two active codes, never zero after success, and on any
	 * failure the transaction is rolled back so the original code stays active.
	 * Concurrent replacements of the same item serialise on the row lock.
	 *
	 * Runs in its own transaction; do not call it inside another open transaction.
	 *
	 * @param int      $product_id  Simple product or variation ID.
	 * @param int      $parent_id   Variation's parent product ID, or 0.
	 * @param string   $new_code    New code (already generated by the caller).
	 * @param int      $user_id     Acting user (recorded as retired_by and created_by).
	 * @param int|null $expected_id Current active code row ID the caller saw, or null to replace whatever is active.
	 * @return int|WP_Error New row ID.
	 */
	public static function replace_active( int $product_id, int $parent_id, string $new_code, int $user_id, ?int $expected_id = null ) {
		global $wpdb;

		$new_code = self::normalize_code( $new_code );

		if ( '' === $new_code ) {
			return new WP_Error( 'pqbg_invalid_code', __( 'Invalid product code format.', 'product-qrcode-barcode-generator' ) );
		}

		if ( $product_id <= 0 || $parent_id < 0 || $parent_id === $product_id || $user_id < 0 ) {
			return new WP_Error( 'pqbg_invalid_item', __( 'Invalid product reference.', 'product-qrcode-barcode-generator' ) );
		}

		$table = Schema::codes_table();
		$now   = current_time( 'mysql', true );

		$wpdb->query( 'START TRANSACTION' );

		// Locks the item's active row; a concurrent replacement waits here until we commit or roll back.
		$current = $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$table} WHERE active_product_id = %d FOR UPDATE", $product_id ) ); // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared -- fixed identifier.

		if ( null === $current ) {
			$wpdb->query( 'ROLLBACK' );
			return new WP_Error( 'pqbg_no_active_code', __( 'This item has no active product code to replace.', 'product-qrcode-barcode-generator' ) );
		}

		if ( null !== $expected_id && (int) $current !== $expected_id ) {
			$wpdb->query( 'ROLLBACK' );
			return new WP_Error( 'pqbg_code_changed', __( 'The product code was changed by another request. Reload the page and try again.', 'product-qrcode-barcode-generator' ) );
		}

		$suppress = $wpdb->suppress_errors( true );

		$retired = $wpdb->query(
			$wpdb->prepare(
				"UPDATE {$table} SET status = %s, active_product_id = NULL, retired_at_gmt = %s, retired_by = %d WHERE id = %d AND status = %s", // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared -- fixed identifier.
				self::STATUS_RETIRED,
				$now,
				$user_id,
				(int) $current,
				self::STATUS_ACTIVE
			)
		);

		$inserted = 1 === $retired ? $wpdb->insert(
			$table,
			array(
				'code'              => $new_code,
				'kind'              => self::KIND_PRODUCT,
				'product_id'        => $product_id,
				'parent_id'         => $parent_id,
				'active_product_id' => $product_id,
				'status'            => self::STATUS_ACTIVE,
				'created_at_gmt'    => $now,
				'created_by'        => $user_id,
			),
			array( '%s', '%s', '%d', '%d', '%d', '%s', '%s', '%d' )
		) : false;

		$wpdb->suppress_errors( $suppress );

		if ( 1 !== $retired || false === $inserted ) {
			$wpdb->query( 'ROLLBACK' );

			return 1 !== $retired
				? new WP_Error( 'pqbg_code_not_active', __( 'The product code is not active.', 'product-qrcode-barcode-generator' ) )
				: new WP_Error( 'pqbg_code_conflict', __( 'The product code could not be saved because it conflicts with an existing code.', 'product-qrcode-barcode-generator' ) );
		}

		$id = (int) $wpdb->insert_id;

		if ( false === $wpdb->query( 'COMMIT' ) ) {
			$wpdb->query( 'ROLLBACK' );
			return new WP_Error( 'pqbg_code_conflict', __( 'The product code could not be saved.', 'product-qrcode-barcode-generator' ) );
		}

		return $id;
	}

	/**
	 * Retires an active code. Retired codes stay in the table for history.
	 *
	 * @param int $code_id Code row ID.
	 * @param int $user_id User retiring the code.
	 * @return true|WP_Error
	 */
	public static function retire( int $code_id, int $user_id ) {
		global $wpdb;

		if ( $code_id <= 0 || $user_id < 0 ) {
			return new WP_Error( 'pqbg_invalid_code_id', __( 'Invalid product code reference.', 'product-qrcode-barcode-generator' ) );
		}

		$table   = Schema::codes_table();
		$updated = $wpdb->query(
			$wpdb->prepare(
				"UPDATE {$table} SET status = %s, active_product_id = NULL, retired_at_gmt = %s, retired_by = %d WHERE id = %d AND status = %s", // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared -- fixed identifier.
				self::STATUS_RETIRED,
				current_time( 'mysql', true ),
				$user_id,
				$code_id,
				self::STATUS_ACTIVE
			)
		);

		if ( 1 !== $updated ) {
			return new WP_Error( 'pqbg_code_not_active', __( 'The product code is not active.', 'product-qrcode-barcode-generator' ) );
		}

		return true;
	}
}
