<?php
/**
 * Data access for dpc_codes, enforcing the one-active-code-per-item invariant
 * in the application layer. The UNIQUE(active_product_id) index and the
 * optional CHECK constraint are defence in depth behind these rules:
 *
 *   - An item (simple product or variation) has at most one active code.
 *   - Creating a code for an item that already has an active one is rejected.
 *   - Retiring clears active_product_id in the same UPDATE.
 *   - There is deliberately no "reactivate": a retired code can never become
 *     active again. Replacing a code means retire + create a new one.
 *
 * This class performs NO capability checks; callers (admin screens, REST
 * routes in later phases) must check Permissions::can_manage_codes() first.
 * It does not generate codes or validate WooCommerce product types either;
 * those belong to the code-generation phase.
 *
 * @package Durga\ProductCodes
 */

namespace Durga\ProductCodes;

use WP_Error;

defined( 'ABSPATH' ) || exit;

/**
 * Reads and writes product-code rows.
 */
final class CodeRepository {

	const KIND_PRODUCT = 'product';

	const STATUS_ACTIVE  = 'active';
	const STATUS_RETIRED = 'retired';

	/** Uppercase letters, digits and inner hyphens, 4-32 chars (e.g. DC-XXXX-XXXX-XXXX). */
	const CODE_PATTERN = '/^[A-Z0-9][A-Z0-9-]{2,30}[A-Z0-9]$/';

	/**
	 * Normalises a code for storage/lookup: trimmed and uppercased. Returns '' when invalid.
	 *
	 * @param string $code Raw code.
	 */
	public static function normalize_code( string $code ): string {
		$code = strtoupper( trim( $code ) );

		return preg_match( self::CODE_PATTERN, $code ) ? $code : '';
	}

	/**
	 * Finds a code row by its code string.
	 *
	 * @param string $code Code string.
	 * @return array<string, string>|null
	 */
	public static function find_by_code( string $code ): ?array {
		global $wpdb;

		$code = self::normalize_code( $code );

		if ( '' === $code ) {
			return null;
		}

		$table = Schema::codes_table();
		$row   = $wpdb->get_row( $wpdb->prepare( "SELECT * FROM {$table} WHERE code = %s", $code ), ARRAY_A ); // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared -- fixed identifier.

		return is_array( $row ) ? $row : null;
	}

	/**
	 * Finds the active code row for a purchasable item.
	 *
	 * @param int $product_id Simple product or variation ID.
	 * @return array<string, string>|null
	 */
	public static function find_active_for_product( int $product_id ): ?array {
		global $wpdb;

		if ( $product_id <= 0 ) {
			return null;
		}

		$table = Schema::codes_table();
		$row   = $wpdb->get_row( $wpdb->prepare( "SELECT * FROM {$table} WHERE active_product_id = %d", $product_id ), ARRAY_A ); // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared -- fixed identifier.

		return is_array( $row ) ? $row : null;
	}

	/**
	 * Inserts a new active code for an item.
	 *
	 * Runs in its own transaction; do not call it inside another open
	 * transaction (START TRANSACTION implicitly commits the outer one).
	 *
	 * @param string $code       Code string (already generated by the caller).
	 * @param int    $product_id Simple product or variation ID.
	 * @param int    $parent_id  Variation's parent product ID, or 0 for simple products.
	 * @param int    $user_id    User creating the code.
	 * @return int|WP_Error New row ID.
	 */
	public static function create_active( string $code, int $product_id, int $parent_id, int $user_id ) {
		global $wpdb;

		$code = self::normalize_code( $code );

		if ( '' === $code ) {
			return new WP_Error( 'dpc_invalid_code', __( 'Invalid product code format.', 'durga-product-codes' ) );
		}

		if ( $product_id <= 0 || $parent_id < 0 || $parent_id === $product_id || $user_id < 0 ) {
			return new WP_Error( 'dpc_invalid_item', __( 'Invalid product reference.', 'durga-product-codes' ) );
		}

		$table = Schema::codes_table();

		$wpdb->query( 'START TRANSACTION' );

		// Locks the item's slot in the unique index so concurrent creators serialise here.
		$existing = $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$table} WHERE active_product_id = %d FOR UPDATE", $product_id ) ); // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared -- fixed identifier.

		if ( null !== $existing ) {
			$wpdb->query( 'ROLLBACK' );
			return new WP_Error( 'dpc_active_code_exists', __( 'This item already has an active product code.', 'durga-product-codes' ) );
		}

		$suppress = $wpdb->suppress_errors( true );
		$inserted = $wpdb->insert(
			$table,
			array(
				'code'              => $code,
				'kind'              => self::KIND_PRODUCT,
				'product_id'        => $product_id,
				'parent_id'         => $parent_id,
				'active_product_id' => $product_id,
				'status'            => self::STATUS_ACTIVE,
				'created_at_gmt'    => current_time( 'mysql', true ),
				'created_by'        => $user_id,
			),
			array( '%s', '%s', '%d', '%d', '%d', '%s', '%s', '%d' )
		);
		$wpdb->suppress_errors( $suppress );

		if ( false === $inserted ) {
			$wpdb->query( 'ROLLBACK' );
			// Unique index on code or active_product_id caught a duplicate/race.
			return new WP_Error( 'dpc_code_conflict', __( 'The product code could not be saved because it conflicts with an existing code.', 'durga-product-codes' ) );
		}

		$id = (int) $wpdb->insert_id;
		$wpdb->query( 'COMMIT' );

		return $id;
	}

	/**
	 * Retires an active code. Retired codes stay in the table for history.
	 *
	 * @param int $code_id Code row ID.
	 * @param int $user_id User retiring the code.
	 * @return true|WP_Error
	 */
	public static function retire( int $code_id, int $user_id ) {
		global $wpdb;

		if ( $code_id <= 0 || $user_id < 0 ) {
			return new WP_Error( 'dpc_invalid_code_id', __( 'Invalid product code reference.', 'durga-product-codes' ) );
		}

		$table   = Schema::codes_table();
		$updated = $wpdb->query(
			$wpdb->prepare(
				"UPDATE {$table} SET status = %s, active_product_id = NULL, retired_at_gmt = %s, retired_by = %d WHERE id = %d AND status = %s", // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared -- fixed identifier.
				self::STATUS_RETIRED,
				current_time( 'mysql', true ),
				$user_id,
				$code_id,
				self::STATUS_ACTIVE
			)
		);

		if ( 1 !== $updated ) {
			return new WP_Error( 'dpc_code_not_active', __( 'The product code is not active.', 'durga-product-codes' ) );
		}

		return true;
	}
}
